<?php
require __DIR__.'/app/bootstrap.php'; hub_require_installed(); hub_require_login();
header('Cache-Control: no-store, private'); header('X-Frame-Options: DENY');
$csrf=hub_csrf_token(); session_write_close();
?>
<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>เชื่อมต่อ Shopee · PAN</title>
<style>
*{box-sizing:border-box}body{font:15px system-ui,Tahoma,sans-serif;background:#f7f8fb;color:#202531;margin:0}main{max-width:1200px;margin:28px auto;padding:0 18px}a{color:#d74224}h1{font-size:26px;margin-bottom:6px}.card{padding:20px;background:white;border:1px solid #e5e7eb;border-radius:14px;margin:16px 0}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}button,input{font:inherit;border:1px solid #ccd0d8;border-radius:8px;padding:10px}button{cursor:pointer;background:#fff}button.primary{background:#ee4d2d;color:white;border-color:#ee4d2d}button:disabled{opacity:.5;cursor:wait}p{line-height:1.7}.muted{color:#687182}#screen{display:block;width:100%;height:auto;touch-action:none;outline:2px solid transparent}#screen:focus{outline-color:#ee4d2d}#screen[hidden]{display:none}#message{white-space:pre-wrap;color:#a33420}#status{white-space:pre-wrap}#text{flex:1;min-width:180px}.tag{font-size:12px;background:#fff0eb;border-radius:20px;padding:5px 10px;color:#ae361b}
</style></head><body><main><a href="./">← กลับ PAN</a><h1>เชื่อมต่อบัญชี Shopee <span class="tag">Server Connector · ทดลองใช้งาน</span></h1><p class="muted">เข้าสู่ระบบครั้งแรก แล้วใช้เซสชันเดิมดึงประวัติจากเซิร์ฟเวอร์ได้ รองรับ Windows และ Ubuntu</p>
<section class="card"><div class="row"><label for="profile">ชื่อโปรไฟล์</label><input id="profile" value="default" maxlength="40" pattern="[a-zA-Z0-9_-]+"><button data-action="open" class="primary">เปิด / เชื่อมบัญชี</button><button data-action="login">เปิดหน้าเข้าสู่ระบบ Shopee</button><button data-action="account">ตรวจบัญชีที่ล็อกอิน</button><button data-action="close">ปิดหน้าต่างและเก็บเซสชัน</button></div><p class="muted">ใช้ชื่อเดิมเพื่อเรียกเซสชันเดิม หรือชื่อใหม่เพื่อแยกบัญชี เปิดได้ครั้งละหนึ่งโปรไฟล์ ปิดหน้าต่างเมื่อใช้งานเสร็จเพื่อให้รอบซิงก์ตามเวลาทำงานได้</p><div id="status" role="status">กำลังตรวจบริการ…</div><p id="access-issue" role="alert" style="background:#fff3cd;color:#754e00;padding:14px;border-radius:8px" hidden></p><p id="account"></p><p id="message" role="alert"></p></section>
<section class="card"><div class="row"><button data-action="check-access">ตรวจสิทธิ์ดึงข้อมูล</button><button data-action="sync" class="primary">ดึงประวัติทั้งหมด</button><button data-action="resume">ทำต่อจากจุดเดิม</button><button data-action="repair">เติมรายละเอียดคำสั่งซื้อ</button><button data-action="pause">หยุดงานชั่วคราว</button><button data-action="purchase">เปิดหน้าการซื้อ</button></div></section>
<section class="card"><h2>หน้าจอ Shopee บนเซิร์ฟเวอร์</h2><p class="muted">คลิกช่องกรอกในภาพ แล้วพิมพ์ผ่านแป้นพิมพ์ หรือส่งข้อความจากช่องด้านล่าง ยืนยัน OTP / QR ด้วยตัวเอง หากมี CAPTCHA ให้ทำตามหน้าจอ ระบบไม่ได้ข้ามการยืนยันของ Shopee</p><img id="screen" alt="หน้าจอเบราว์เซอร์ Shopee บนเซิร์ฟเวอร์" tabindex="0" hidden draggable="false"><p id="screen-note" class="muted">กดเปิด / เชื่อมบัญชี เพื่อแสดงหน้าจอ</p><div class="row"><input id="text" type="password" autocomplete="off" placeholder="ข้อความ / รหัสผ่าน / OTP ที่จะส่งไปช่องที่เลือก"><button id="send">ส่งข้อความ</button><button data-key="Tab">Tab</button><button data-key="Enter">Enter</button><button data-key="Backspace">ลบ</button><button data-key="Control+A">เลือกทั้งหมด</button><button data-scroll="-500">เลื่อนขึ้น</button><button data-scroll="500">เลื่อนลง</button></div></section>
</main><script>window.panShopeeCsrf=<?=json_encode($csrf)?>;</script><script src="./assets/shopee-server.js"></script></body></html>
