const $=id=>document.getElementById(id);let currentAccount=null,currentState={};
const log=s=>{$('log').textContent=s};
async function activeShopee(){let [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab||!/https:\/\/([^.]+\.)?shopee\.co\.th\//.test(tab.url||''))throw new Error('กรุณาเปิด shopee.co.th และ Login ก่อน');if(!/\/user\/purchase/.test(tab.url||'')){tab=await chrome.tabs.update(tab.id,{url:'https://shopee.co.th/user/purchase/'});const until=Date.now()+15000;while(Date.now()<until){const t=await chrome.tabs.get(tab.id);if(t.status==='complete'){tab=t;break;}await new Promise(r=>setTimeout(r,250));}await new Promise(r=>setTimeout(r,700));}return tab;}
async function refreshAccount(){try{const t=await activeShopee(),r=await chrome.runtime.sendMessage({type:'GET_ACCOUNT',tabId:t.id});if(!r.ok)throw new Error(r.error);currentAccount=r.account;render(r.state||{});$('account').textContent=currentAccount.username||currentAccount.nickname||currentAccount.userid;return t;}catch(e){$('account').textContent='ยังไม่พร้อม';log(String(e.message||e));return null;}}
function render(s){currentState=s||{};$('state').textContent=s.error?'ผิดพลาด':s.done?'เสร็จแล้ว':s.running?'กำลังทำงาน':s.paused?'หยุดชั่วคราว':'พร้อม';$('shopeeRecords').textContent=s.shopeeRecords||0;$('shopeeUnique').textContent=s.shopeeUniqueOrders||0;$('panOrders').textContent=s.panOrders??0;$('panInserted').textContent=s.panInsertedOrders||0;$('panUpdated').textContent=s.panUpdatedOrders||0;$('duplicateRecords').textContent=s.duplicateRecords||0;$('items').textContent=(s.items||0)+' items';$('ignored').textContent=s.ignored||0;$('cancelled').textContent=s.cancelled||0;$('cancelledDeleted').textContent=s.cancelledDeleted||0;$('repair').textContent=`${s.repairDone||0} / ${s.repairTotal||0}`;$('autoDetail').textContent=s.autoDetailUpdated||0;$('autoDetailErrors').textContent=s.autoDetailErrors||0;$('productEnrich').textContent=s.productEnrichDone||0;$('productEnrichErrors').textContent=s.productEnrichErrors||0;const pct=s.job==='repair'&&s.repairTotal?Math.round((s.repairDone||0)/s.repairTotal*100):s.done?100:s.running?55:0;$('prog').value=pct;$('cursor').textContent=s.job==='recent'?`pages ${s.pages||0} · ตั้งแต่ ${s.cutoff||'เริ่มต้น'} · next ${s.recentOffset||0}`:s.apiMode==='status'?`pages ${s.pages||0} · status type ${[3,7,8,12,4,9][s.statusIndex||0]??'done'} · next ${s.statusOffset??0}`:`pages ${s.pages||0} · next offset ${s.offset??0}`;log((s.error||s.status||'พร้อมใช้งาน')+(s.lastRepairError?'\n\nเติมรายละเอียดล่าสุด: '+s.lastRepairError:'')+(s.lastAutoDetailError?'\n\nAuto Detail ล่าสุด: '+s.lastAutoDetailError:'')+(s.lastProductEnrichError?'\n\nหมวดสินค้าล่าสุด: '+s.lastProductEnrichError:''));}
async function copyText(text){try{await navigator.clipboard.writeText(text);log('คัดลอกแล้ว\n\n'+text.slice(0,1200));}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();}}
$('hub').addEventListener('change',()=>chrome.storage.local.set({hubUrl:$('hub').value.replace(/\/$/,'' )}));
$('apiKey').addEventListener('change',()=>chrome.storage.local.set({apiKey:$('apiKey').value.trim()}));
$('check').onclick=async()=>{try{const u=$('hub').value.replace(/\/$/,'');await chrome.storage.local.set({hubUrl:u});const k=$('apiKey').value.trim();await chrome.storage.local.set({apiKey:k});const r=await fetch(u+'/api/status.php',{headers:{'X-PAN-Key':k}});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||`PAN HTTP ${r.status}`);log(`PAN พร้อม · v${j.version} · ${String(j.database||'').toUpperCase()} · ${j.purchase_orders??j.orders} Purchase Orders · ${j.accounts} accounts`)}catch(e){log('เชื่อมต่อ PAN ไม่ได้: '+e)}};
$('start').onclick=async()=>{try{const t=await refreshAccount();if(!t)return;await chrome.storage.local.set({hubUrl:$('hub').value.replace(/\/$/,''),apiKey:$('apiKey').value.trim()});await chrome.runtime.sendMessage({type:'START_SYNC',tabId:t.id});log('เริ่มดึงประวัติทั้งหมดแล้ว')}catch(e){log(String(e))}};
$('recent').onclick=async()=>{try{const t=await refreshAccount();if(!t)return;await chrome.storage.local.set({hubUrl:$('hub').value.replace(/\/$/,''),apiKey:$('apiKey').value.trim()});const r=await chrome.runtime.sendMessage({type:'START_RECENT',tabId:t.id});if(!r.ok)throw new Error(r.error);log('กำลังอ่านจุดเริ่มต้นจาก PAN เพื่ออัปเดตเฉพาะช่วงล่าสุด')}catch(e){log(String(e.message||e))}};
$('resume').onclick=async()=>{try{const t=await refreshAccount();if(t)await chrome.runtime.sendMessage({type:'RESUME_SYNC',tabId:t.id})}catch(e){log(String(e))}};
$('repairBtn').onclick=async()=>{try{const t=await refreshAccount();if(t)await chrome.runtime.sendMessage({type:'START_REPAIR',tabId:t.id})}catch(e){log(String(e))}};
$('productEnrichBtn').onclick=async()=>{try{const t=await refreshAccount();if(t)await chrome.runtime.sendMessage({type:'START_PRODUCT_ENRICH',tabId:t.id})}catch(e){log(String(e))}};
$('repairAllBtn').onclick=async()=>{if(!confirm('จะเติม Order Detail ใหม่ทั้งหมดของบัญชีนี้ อาจใช้เวลานานและยิง Shopee API จำนวนมาก ต้องการทำต่อหรือไม่?'))return;try{const t=await refreshAccount();if(t)await chrome.runtime.sendMessage({type:'START_REPAIR_ALL',tabId:t.id})}catch(e){log(String(e))}};
$('pause').onclick=()=>chrome.runtime.sendMessage({type:'PAUSE_SYNC'});
$('reset').onclick=async()=>{if(!currentAccount)return;await chrome.runtime.sendMessage({type:'RESET_SYNC',accountId:String(currentAccount.userid)});render({});};
$('copyError').onclick=()=>copyText(String(currentState.error||currentState.lastRepairError||currentState.status||'ไม่มี error'));
$('copyDebug').onclick=()=>copyText(JSON.stringify({version:'2.4.10',account:currentAccount,state:currentState},null,2));
chrome.runtime.onMessage.addListener(m=>{if(m?.type==='SYNC_PROGRESS'&&(!currentAccount||String(m.state?.accountId||'')===String(currentAccount.userid)))render(m.state)});
chrome.runtime.onMessage.addListener(m=>{if(m?.type==='SYNC_ERROR')log(m.error)});
(async()=>{const c=await chrome.storage.local.get(['hubUrl','apiKey']);$('hub').value=c.hubUrl||'https://pan.itoom.work';$('apiKey').value=c.apiKey||'';await refreshAccount()})();
